---
name: FeatureReport
description: File a bug report
title: "Feature: "
labels: ["bug", "triage"]
projects: ["octo-org/1", "octo-org/44"]
assignees: 
  - octocat
body:

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: What is your name?
      placeholder: ex. email@example.com
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        
  - type: dropdown
    id: Typefeature
    attributes:
      label: Type of request
      description: Select the type of your request
      options:
        - New Feature (Default)
        - Noob Feature (Edge)
      default: New Feature (Default)
    validations:
      required: true
 
  - type: dropdown
    id: os
    attributes:
      label: What is the OS you want to suggest?
      multiple: true
      options:
        - ios
        - windows
        - linux
 
  - type: textarea
    id: details
    attributes:
      label: What are the details of your suggestion?
      description: Explain what you want
      render: shell
---
